repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: local
    hooks:
    -   id: export-requirements
        name: Convert pyproject.toml to requirements.txt
        language: system
        entry: poetry export --with dev -f requirements.txt --without-hashes --output requirements.txt
        files: "^pyproject.toml$"
        pass_filenames: false