# docker-compose.yml

version: '3'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ci-template

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ci-template

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ci-template

networks:
  ci-template:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
